on:
  release:
    types:
    - published
name: Build Release
jobs:
  release-assests:
    name: release kubectl-karmada
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - karmadactl
          - kubectl-karmada
        os:
          - linux
          - darwin
        arch:
          - amd64
          - arm64
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4
  update-crds:
    needs: release-assests
    name: Upload crd assests
    runs-on: ubuntu-20.04
    steps:
    - uses: a7ul/tar-action@v1.1.0
      with:
        command: x
        cwd: ./charts/karmada/_crds
        files: crds.tar.gz
