on:
  release:
    types:
    - published
name: Build Release
jobs:
  release-assests:
    name: release kubectl-karmada
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - karmadactl
        os:
          - linux
        arch:
          - amd64
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4
  update-crds:
    needs: release-assests
    name: Upload crd assests
    runs-on: ubuntu-20.04
    steps:
    - run: |
        mv ./charts/karmada/_crds ./charts/karmada/crds

    - uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: ./charts/karmada/
        files: crds
        outPath: crds.tar.gz
